# use node public image
FROM node:latest

# define project folder
WORKDIR /usr/app

# copy project files
COPY package.json package.json
COPY tsconfig.json tsconfig.json
COPY server.ts server.ts

# install dependencies
RUN npm install

# --legacy-watch used for Windaube 
# See for more details : https://stackoverflow.com/questions/39239686/nodemon-doesnt-restart-in-windows-docker-environment
CMD npx nodemon --legacy-watch --exec ts-node server.ts