version: '3'
services:
    front:
        image: backtrack5r3/exam_front:1.0-dev
        ports:
            - "80:80"
    back:
        image: backtrack5r3/exam_back:1.0-dev
        ports:
            - "3000:3000"